### PR TITLE
Update package name

### PR DESCRIPTION
**Pull request by hasit**
Change package name 'golang' to 'navigator-godef' to show keybindings in the package settings page. Refer to [Keybindings won’t show in settings](https://discuss.atom.io/t/keybindings-wont-show-in-settings/28024) discussion on [discuss.atom.io](discuss.atom.io).

### CODE REVIEW

**Comment by joefitzgerald** [comment]
👎  this is by design. All go-plus packages use `golang` as the command prefix.

**Comment by joefitzgerald** [comment]
Thanks for the contribution though - sorry to 👎  it!!!

**Comment by hasit** [comment]
No problem. Is there a way to make the keybindings show without the this change?

**Comment by joefitzgerald** [comment]
What do you mean? They already show when you type `golang` after you type CMD-SHIFT-P.

**Comment by hasit** [comment]
I mean in in the package settings page. For example, ['git-projects'](https://github.com/prrrnd/atom-git-projects) package has a section for 'Keybindings' that show up in the settings page.

When I install a new package, I go through its settings first. This is where I learn about the keybindings. My only concern is that the keybindings aren't listed anywhere in navigtor-godef. I would suggest you add the a list of keybindings to the README.md file for easy access.

**Comment by joefitzgerald** [comment]
You know I didn't think about that implication. It would be really nice to be able to associate the keybindings back with the package name such that they show up in package settings. I'll bring this up with the Atom core team.

**Comment by hasit** [comment]
I posted an issue already https://github.com/atom/settings-view/issues/772.

Thank you for your continued support for golang on Atom. I love your work and use it regularly. 👍

**Pull request closed without merging**
